### ISSUE TITLE
Types not quite what i'd expect

### ISSUE THREAD

**Issue by mobob** [jharlow/zod-to-dynamodb-onetable-schema#31] opened 2024-11-07 15:38 UTC
Hey! Cool project, i'm a fan of onetable and have been mixing more zod in, so thought i'd give this a go.

I have some zod schema defined in a shared package in my monorepo, so i pull this in, then i added this chunk into my mega one table schema:

```typescript
    Feedback: zodOneModelSchema(
      FeedbackRequestSchema.extend({
        pk: z.literal('FB#${feedbackId}'),
        sk: z.literal('TYPE#${_type}#VID#${_vendorListingId}'),
      }),
    ) as OneModel,
```

The casting to OneModel seemed necessary, it really broke the bounds of the overall structure without it.

And then further down i have a type for this entity:

```typescript
export type FeedbackEntity = Entity<typeof FstaSchema.models.Feedback>;
export function modelFeedback(): Model<FeedbackEntity> {
  return ddbGlobalTable().getModel<FeedbackEntity>('Feedback');
}
```

However, when i try to use this (hover in vscode), it shows the type of these Entity objects is pretty unknown:

```typescript
(alias) type FeedbackEntity = {
    [x: string]: undefined;
}
import FeedbackEntity
```

Whereas hovering over a different type that is not defined with zod and more explitily, you see all the bits, ie:
```typescript
type BookingEntity = {
    bookingStatus: BookingStatus;
    created?: Date | undefined;
    updated?: Date | undefined;
    pk?: string | undefined;
    sk?: string | undefined;
    state?: string | undefined;
    bookingSummary?: string | undefined;
}
```

Is there any way to make this less opaque?

If you have any pointers let me know!

**Comment by jharlow** [comment] 2024-11-14 16:31
Hi @mobob, thanks for trying it out and providing feedback. The package should be designed to give you native typing with no need for casting, so this is something I'd like to understand why you aren't getting that benefit.

I have a few questions so I can do a better investigation:

1. Can I just confirm that you're using compatible `zod` and `dynamodb-onetable` versions? Aka,  compatible with `zod@^3.23.8` and `dynamo-onetable@^2.7.5`.

2. Can I see the definition of `FeedbackRequestSchema`? I wonder if this is caused by some kind of incompatibility. On that note, what happens at that code-snippet at runtime with a logger instance? I baked in a lot of `logger.warn`/`Error`s for when a `zod` type can't be coerced into a `dynamodb-onetable` schema.

```ts
it('runtime test', () => {
zodOneModelSchema(
 FeedbackRequestSchema.extend({
   pk: z.literal('FB#${feedbackId}'),
   sk: z.literal('TYPE#${_type}#VID#${_vendorListingId}'),
 }),
 { logger } // 👈 winston Logger here
)
})
```

3. If you have time, would you pull this repo and just hover/try the typing in some of the model examples set up in `test/zodOneModelSchema.spec.ts`? Those are typing correctly as you expect for me, if they aren't for you it would help me narrow down on testing with different language server protocols.

Thanks again for the feedback, I hope I can help out!

**Comment by jharlow** [comment] 2024-11-15 02:08
@mobob I've pulled this repo into my own VSCode (normally I use `nvim`) and IntelliJ Webstorm and the typing seems to be working for me. Looking forward to seeing that `FeedbackRequestSchema` is so I can try and do a reproduction of the issue.

**Comment by mobob** [comment] 2024-11-20 02:53
Hey Thanks so much for the suggestions, sorry it toook a bit to get back @jharlow 

I actually think...  it might be working now? User error for sure! Here is the schema as i had defined it:

```
import { z } from 'zod';

export enum FeedbackTypeEnum {
  GENERAL = 'GENERAL',
  EXIT_EARLY = 'EXIT_EARLY',
  FEEDBACK_AT_COMPLETION = 'FEEDBACK_AT_COMPLETION',
}

export const FeedbackTypeSchema = z.enum([FeedbackTypeEnum.GENERAL, FeedbackTypeEnum.EXIT_EARLY, FeedbackTypeEnum.FEEDBACK_AT_COMPLETION]);

export const FeedbackRequestSchema = z.object({
  vendorListingId: z.string().optional(),
  chatId: z.string().optional(),
  clientMetadata: z.record(z.any()).optional(),
  feedbackType: FeedbackTypeSchema,
  data: z.record(z.any()),
});

export type FeedbackRequest = z.infer<typeof FeedbackRequestSchema>;
```

However this isn't likely to work exactly as i wanted it as there is a FeedbackId i haven't figured out how to add to zod but have its ulid generated, like so (in non zod land):

```
    Feedback: {
      pk: { type: String, value: 'FB#${feedbackId}' },
      sk: { type: String, value: 'VID#${vendorListingId}' },
      feedbackId: { type: String, generate: 'ulid', required: true },
      feedbackType: { type: String, required: true },
      vendorListingId: { type: String, required: true, default: 'NONE' },
      chatId: { type: String },
      data: { type: Object },
      clientMetadata: { type: Object },
    } as const,
```

And what i have, which clearly won't work as i'm not specifying feedbackId...  

```
 Feedback: zodOneModelSchema(
      FeedbackRequestSchema.extend({
        pk: z.literal('FB#${feedbackId}'),
        sk: z.literal('VID#${vendorListingId}'),
      }),
    )
```

Any tips on how to specify generated fields?

No linting errors with this at the moment tho, so definitely can close this. I'll play some more with it. I have dozens of models in my schema so might do some piecemeal moving over and see how it goes (its great that that is possible!).    

For the record, attached is a screenshot of how types show up for me in your repo. Does it look right?

<img width="708" alt="Screenshot 2024-11-19 at 9 29 13 PM" src="https://github.com/user-attachments/assets/7ccd27eb-51e2-4257-bfe6-bcf6aa9cbe06">

Thanks again so much!

**Comment by jharlow** [comment] 2024-11-20 19:34
Thanks for the response @mobob! I'm glad that things are working a little better for you now.

It's a good question re: `generated` fields. One of the boundaries I envision for this library is that it is solely responsible for transforming `zod` schemas into `dynamodb-onetable` schemas. Since `zod` doesn't expose a convincing parallel to a `generate` field in its API, I think this might be out of scope for this library.

Still, this is obviously a common usecase, and it's why I expose `zodToOneField` as part of the libs API. Here's a working test I mocked quickly using your schema:

```ts
it("mobob test", () => {
  // Assemble
  enum FeedbackTypeEnum {
    GENERAL = 'GENERAL',
    EXIT_EARLY = 'EXIT_EARLY',
    FEEDBACK_AT_COMPLETION = 'FEEDBACK_AT_COMPLETION',
  }

  const FeedbackRequestSchema = z.object({
    vendorListingId: z.string(),
    chatId: z.string().optional(),
    clientMetadata: z.record(z.any()).optional(),
    feedbackType: z.nativeEnum(FeedbackTypeEnum),
    data: z.record(z.any()),
  });

  // Act
  const oneModel = {
    ...zodOneModelSchema(FeedbackRequestSchema.extend({
      pk: z.literal('FB#${feedbackId}'),
      sk: z.literal('VID#${vendorListingId}'),
    })),
    feedbackId: { ...zodOneFieldSchema(z.string()), generate: 'ulid' },
  } as const

  // Assert
  expect(oneModel).toEqual({
    pk: { type: "string", value: 'FB#${feedbackId}', required: true },
    sk: { type: "string", value: 'VID#${vendorListingId}', required: true },
    feedbackId: { type: "string", generate: 'ulid', required: true },
    feedbackType: { type: "string", required: true, enum: ["GENERAL", "EXIT_EARLY", "FEEDBACK_AT_COMPLETION"] },
    vendorListingId: { type: "string", required: true },
    chatId: { type: "string" },
    data: { type: "object", required: true },
    clientMetadata: { type: "object" },
  })
});

```

A few things of note here:
1. I had to make a couple of adjustments to your `zod` schema. I had to set the `vendorListingId` as required (I think) because it is used to generate the `sk`, and I used `z.nativeEnum` to avoid `FeedbackTypeSchema`.
2. The model in the assertion is different to the version you defined by hand. There are a few additional `required: true` fields correctly infered from your `zod` schema, and notice the enum has been correctly cast into the `enum` slot in `feedbackType`

I was then able to set up a `Table` client interface that gave me correct typing for the above `oneModel`.

```ts
const makeZodSchema = <T>(models: T) => ({
  format: "onetable:1.1.0",
  version: "0.0.1",
  indexes: { primary: { hash: "pk", sort: "sk" } },
  models,
  params: { isoDates: false, timestamps: true, null: true },
});

const schema = makeZodSchema({ Feedback: oneModel, });

const table = new Table({ schema, name: 'test' });

const model = table.getModel("Feedback");

// I got correct type inference in `.create`
const exampleRecord = model.create({ data: {}, feedbackType: FeedbackTypeEnum.GENERAL, vendorListingId: "test" });
```

Finally, another approach could be to define `oneModel` like this:

```ts
  const FeedbackModelSchema = FeedbackRequestSchema.extend({
    pk: z.literal('FB#${feedbackId}'),
    sk: z.literal('VID#${vendorListingId}'),
    feedbackId: z.string()
  })

  // Act
  const oneModel = {
    ...zodOneModelSchema(FeedbackModelSchema),
    feedbackId: { ...zodOneFieldSchema(FeedbackModelSchema.shape.feedbackId), generate: 'ulid' },
  } as const
```

So there's still one source of truth for the Dynamo model.

I hope that helps. Apologies, I know that spread syntax isn't very pretty. Perhaps I could cook up a utility function for model adornments, but barring extra work that's my best solution. Let me know if that works for you and if it does I'll close the issue.

**Closed** 2024-11-23 04:00 UTC
Labels: bug
